### ISSUE TITLE
Preprocess_Gene_module error

### ISSUE THREAD

**Issue by SopjudeS** [cmzuo11/stKeep#1]
Thank you for this powerful tool! I ran this on my own 10x data. I encountered an error when running the Preprocess_Gene_module.py.

![图片](https://github.com/cmzuo11/stKeep/assets/166676441/66b11cbc-9a0c-4e5e-bfc9-37c236c3e7bb)

I checked the source code.  Is there a problem with the initial dimensions set for gene_spot_adj?

**Comment by JunjieXia14** [comment]
Thanks so much for your interest and feedback. 
I am sorry for the overlook, and I have revised the code to make it run smoothly. 

Best,
Chunman

**Comment by cmzuo11** [comment]
Thanks so much for your interest and feedback. 
I am sorry for the overlook, and I have revised the code to make it run smoothly. 

Best,
Chunman

**Comment by SopjudeS** [comment]
Thank you for your prompt response. However, I encountered another error:
Traceback (most recent call last):
  File "Preprocess_Cell_module.py", line 65, in <module>
    stKeep.RNA_encoding_train(args, adata2 )
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/stKeep/model_training.py", line 227, in RNA_encoding_train
    train           = data_utils.TensorDataset( torch.from_numpy( sp.csr_matrix.toarray(adata[train_index].X) ),
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1109, in __getitem__
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/anndata/_core/anndata.py", line 289, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/anndata/_core/anndata.py", line 336, in _init_as_view
    obs_sub = adata_ref.obs.iloc[oidx]
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/pandas/core/indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/pandas/core/indexing.py", line 1647, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/ubuntu/anaconda3/envs/stKeep/lib/python3.8/site-packages/pandas/core/indexing.py", line 1621, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds.

I suspect the issue lies within the RNA_encoding_train function. After obtaining the index, the filtering step might cause some spots to be removed. Is it possible to perform the filtering right after initially loading the data?
![图片](https://github.com/cmzuo11/stKeep/assets/166676441/9c764cf9-4afa-4b13-a74b-f135fe36e973)
I have several questions:

If I have multiple samples, how should I choose the highly variable genes (HVGs)? In my dataset, there are only a few intersecting HVGs across different samples.
How can I integrate the representations from different samples?
Are the CCC_module_LRP_strength values comparable between different samples?

Thank you!

**Comment by cmzuo11** [comment]
I can’t reproduce your errors. Could you try setting test_size_prop to 0 and then check if the issue persists?
Here are my suggestions for each of your questions:
(1) I suggest keeping more HVGs for each sample, ensuring that the number of intersecting HVGs across diverse samples is around 1000, or adjusting based on your data; and 
(2) and (3) stKeep is designed to dissect intra-tumor heterogeneity by identifying cell-modules, gene-modules, and CCC modules from one slice, rather than integrating multiple slices. However, I suggest using other tools to identify your spatial clusters of interest, and then applying stKeep to analyze molecular networks or CCC patterns within these niches.

Best,
Chunman

**Comment by SopjudeS** [comment]
Thank you for your response. Setting test_size_prop to 0 did not work. However, after filtering the data with sc.pp.filter_cells(adata, min_genes=100) post-loading, it worked as expected.

**Comment by cmzuo11** [comment]
Thank you so much for your feedback. I have now added the code to the corresponding locations. I performed most of the operations in Seurat and missed some steps when wrapping them in Scanpy. I apologize for any inconvenience this may have caused.

Best regards,
Chunman

**Comment by SopjudeS** [comment]
Thank you! I noticed that you only added the code to Preprocess_Cell_module.py. The same modifications should be made to Preprocess_Gene_module.py to avoid encountering another error. This will ensure consistency and prevent potential issues during preprocessing.

**Comment by cmzuo11** [comment]
Ok, I have added it.
